Rcf drive
Team293/ChargedUp pull request #27
Opened 2023-02-13 21:36 UTC by PillageDev

# Purpose: Adding RCF Drive

# Files Changed: 
- Constants.java: Added joystick default deadband
- Robot.java: Set the default drive when teleop starts
- RobotContainer.java: Added option to change drive type in smartdashboard; sets default drive to option selected in smartdashboard
- ArcadeDrive.java: Removed forza drive logic
- ForzaDrive.java: Transferring forza drive logic to new file
- RCFDrive.java:  Added RCF Drive logic
- Drivetrain.java: Moved Arcade Drive method to Drivetrain.java

2023-02-13 21:55 UTC, bjmcternan requested changes
Just one comment to address. When we do we can merge it

2023-02-13 21:55 UTC, bjmcternan commented on src/main/java/frc/robot/RobotContainer.java
> +    SmartDashboard.putData("ArcadeDrive", new ForzaDrive(m_drivetrain, m_driverXboxController));
Is this needed? Wont the sendable chooser allow us to select the drive type?

2023-02-16 21:18 UTC, PranjalMhetre reviewed
Still in testing phase.

2023-02-16 21:24 UTC, closed without merging

2023-02-16 21:24 UTC, bjmcternan commented
We can open it when out of the testing phase @PranjalMhetre

2023-02-16 21:24 UTC, bjmcternan commented
Just click the "Reopen and comment" button down at the bottom of this chat