Can ids
Team293/ChargedUp pull request #40
Opened 2023-02-25 18:14 UTC by PranjalMhetre

Changed the Can IDs of the new motors to what we set them in the phoenix tuner.

2023-02-25 18:40 UTC, bjmcternan commented
Please rename shoulder to pivot and reach to extender

2023-02-26 01:32 UTC, bjmcternan requested changes
This probably doesn't build. There is a typo on one of the variable names

2023-02-26 20:07 UTC, PillageDev commented on src/main/java/frc/robot/subsystems/Arm.java
> +        pivotTalonFX = new WPI_TalonFX(_TALON_FX_CAN_ID);
Fixed

2023-02-27 01:11 UTC, bjmcternan requested changes

2023-02-27 01:11 UTC, bjmcternan commented on src/main/java/frc/robot/subsystems/Arm.java
> +    public static final int _TALON_FX_CAN_ID = 4;
Typo, this probably doesn't build!

2023-02-27 21:38 UTC, rohanmishr commented on src/main/java/frc/robot/subsystems/Arm.java
> +        pivotTalonFX = new WPI_TalonFX(_TALON_FX_CAN_ID);
Deleted _TALON_FX_CAN_ID (line 62) because it wasn't being used, and reassigned the can IDs (lines 11 + 12) to the correct ones.

2023-02-27 22:12 UTC, bjmcternan approved these changes
Looks good to me

2023-02-28 15:28 UTC, LavaWaffle approved these changes
Looks great

2023-03-01 00:02 UTC, merged